### ISSUE TITLE
document not cover all the parameters

### ISSUE THREAD

**Issue by beyondpie** [xyz111131/SIMPLEs#2]
Hi, Zhirui,

I'm now moving all the docuemnts in the codes based on roxygen. I notice that the original man document doesn't cover all the parameters in a function.
For example, do_impute, you also have several MCMC related parameters. I think we should mention them in our document, right?

Songpeng

**Comment by beyondpie** [comment]
Also, from your namespace, you only output the do_impute and two functions for simples. No EM_impute or ztruct like function in the namespace. In this way, I think we should delete the documents specific for them, right? Since you don't want the user uses it.

**Comment by xyz111131** [comment]
Yes.
